import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en' | 'ar' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traductions
const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    
    // Footer
    'footer.quickLinks': 'Liens Rapides',
    'footer.services': 'Nos Services',
    'footer.contact': 'Contact',
    'footer.aboutUs': 'À propos de nous',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.privacy': 'Politique de confidentialité',
    'footer.copyright': '© 2025 BTK Agency. Tous droits réservés.',
    'footer.description': 'Votre partenaire digital pour transformer votre présence en ligne.',
    
    // Services
    'services.title': 'Nos Services',
    'services.subtitle': 'Des solutions digitales complètes pour transformer votre présence en ligne et atteindre vos objectifs business.',
    'services.seo.title': 'Optimisation SEO',
    'services.seo.description': 'Améliorez votre classement dans les moteurs de recherche et générez du trafic organique avec nos stratégies SEO éprouvées.',
    'services.advertising.title': 'Publicité Digitale',
    'services.advertising.description': 'Maximisez votre ROI avec des campagnes publicitaires ciblées sur toutes les plateformes majeures.',
    'services.design.title': 'Design de Marque',
    'services.design.description': 'Créez une identité de marque mémorable qui résonne avec votre audience cible.',
    'services.web.title': 'Développement Web',
    'services.web.description': 'Construisez des sites web rapides et responsifs qui convertissent les visiteurs en clients.',
    'services.analytics.title': 'Analyses et Insights',
    'services.analytics.description': 'Transformez les données en insights actionnables pour optimiser vos performances digitales.',
    'services.social.title': 'Marketing Réseaux Sociaux',
    'services.social.description': 'Engagez votre audience et construisez des connexions significatives sur les plateformes sociales.',
    
    // Hero
    'hero.title': 'Votre Croissance Digitale,Notre Expertise',
    'hero.subtitle': 'Transformez votre marque avec des stratégies de marketing digital de pointe. Nous créons des campagnes convaincantes qui génèrent des résultats et stimulent votre croissance business.',
    'hero.cta': 'Commencer aujourd\'hui',
    'hero.watchStory': 'Voir notre histoire',
    'hero.happyClients': 'Clients Satisfaits',
    'hero.projectsCompleted': 'Projets Réalisés',
    'hero.successRate': 'Taux de Réussite',
    'hero.support': 'Support',
    
    // About
    'about.title': 'À propos de BTK Agency',
    'about.subtitle': 'Nous sommes une agence de marketing digital visionnaire dédiée à transformer les entreprises grâce à des stratégies innovantes et une technologie de pointe.',
    'about.learnStory': 'Découvrir notre histoire',
    'about.happyClients': 'Clients Satisfaits',
    'about.projectsCompleted': 'Projets Réalisés',
    'about.successRate': 'Taux de Réussite',
    'about.yearsExperience': 'Années d\'Expérience',
    'about.innovationFirst': 'Innovation en Premier',
    'about.innovationFirstDesc': 'Nous restons en avance sur les tendances digitales pour livrer des solutions de pointe qui vous donnent un avantage concurrentiel.',
    'about.resultsDriven': 'Axé sur les Résultats',
    'about.resultsDrivenDesc': 'Chaque stratégie que nous implémentons est conçue pour livrer des résultats mesurables et maximiser votre retour sur investissement.',
    'about.clientPartnership': 'Partenariat Client',
    'about.clientPartnershipDesc': 'Nous croyons en la construction de partenariats à long terme, travaillant étroitement avec vous pour comprendre et atteindre vos objectifs.',
    'about.transparentProcess': 'Processus Transparent',
    'about.transparentProcessDesc': 'Transparence complète dans nos processus, tarifs et résultats. Vous saurez toujours exactement ce que nous faisons et pourquoi.',
    
    // Contact
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Prêt à transformer votre business ? Parlons-en !',
    'contact.email.title': 'Envoyez-nous un email',
    'contact.email.description': 'Envoyez-nous un email à tout moment',
    'contact.phone.title': 'Appelez-nous',
    'contact.phone.description': 'Lun-Ven de 8h à 18h',
    'contact.address.title': 'Visitez-nous',
    'contact.hours.title': 'Heures de travail',
    'contact.hours.days': 'Lundi - Vendredi',
    'contact.hours.time': '8:00 - 18:00 GMT+1',
    'contact.form.name': 'Nom',
    'contact.form.namePlaceholder': 'Votre nom',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'votre@email.com',
    'contact.form.subject': 'Sujet',
    'contact.form.subjectPlaceholder': 'Comment pouvons-nous vous aider ?',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Parlez-nous de votre projet...',
    'contact.form.send': 'Envoyer le message',
    
    // Common
    'learnMore': 'En savoir plus',
    'getStarted': 'Commencer',
    'contactUs': 'Nous contacter',
    'language': 'Langue',
    
    // Portfolio
    'portfolio.title': 'Notre Portfolio',
    'portfolio.subtitle': 'Découvrez nos projets les plus marquants et l\'impact que nous avons créé pour nos clients.',
    'portfolio.filters.all': 'Tous les Projets',
    'portfolio.filters.web': 'Développement Web',
    'portfolio.filters.branding': 'Design de Marque',
    'portfolio.filters.marketing': 'Marketing Digital',
    'portfolio.filters.seo': 'SEO',
    'portfolio.viewProject': 'Voir le Projet',
    'portfolio.technologies': 'Technologies',
    'portfolio.results': 'Résultats',
    'portfolio.testimonial': 'Témoignage',
    'portfolio.loadMore': 'Charger plus de projets',
    'portfolio.downloadPDF': 'Télécharger Portfolio PDF',
    
    // Portfolio Projects
    'portfolio.projects.ecommerce.title': 'Refonte Plateforme E-Commerce',
    'portfolio.projects.ecommerce.client': 'TechCorp Inc.',
    'portfolio.projects.ecommerce.description': 'Refonte complète et développement d\'une plateforme e-commerce moderne avec une expérience utilisateur améliorée et des taux de conversion augmentés.',
    'portfolio.projects.ecommerce.testimonial': 'BTK Agency a complètement transformé notre présence en ligne. La nouvelle plateforme a augmenté nos ventes de 120% en seulement 6 mois.',
    'portfolio.projects.ecommerce.author': 'Sarah Johnson',
    'portfolio.projects.ecommerce.position': 'CEO, TechCorp Inc.',
    
    'portfolio.projects.branding.title': 'Identité de Marque & Campagne Marketing',
    'portfolio.projects.branding.client': 'GreenLife Organics',
    'portfolio.projects.branding.description': 'Design d\'identité de marque complet et campagne de marketing digital pour une entreprise d\'aliments biologiques.',
    'portfolio.projects.branding.testimonial': 'La transformation de la marque a dépassé nos attentes. Notre engagement sur les réseaux sociaux a augmenté de 150%.',
    'portfolio.projects.branding.author': 'Michael Chen',
    'portfolio.projects.branding.position': 'Directeur Marketing, GreenLife',
    
    'portfolio.projects.seo.title': 'Optimisation SEO & Stratégie de Contenu',
    'portfolio.projects.seo.client': 'LegalAdvice Pro',
    'portfolio.projects.seo.description': 'Stratégie SEO complète et optimisation de contenu pour un site web de services juridiques.',
    'portfolio.projects.seo.testimonial': 'Notre trafic organique a augmenté de 200% et nous sommes maintenant classés pour tous nos mots-clés cibles.',
    'portfolio.projects.seo.author': 'David Rodriguez',
    'portfolio.projects.seo.position': 'Fondateur, LegalAdvice Pro',
    
    'portfolio.projects.advertising.title': 'Campagne Publicité Digitale',
    'portfolio.projects.advertising.client': 'FitnessFlow',
    'portfolio.projects.advertising.description': 'Campagne publicitaire multi-canal pour une application fitness avec segmentation d\'audience ciblée.',
    'portfolio.projects.advertising.testimonial': 'La campagne a livré un ROI exceptionnel. Nous avons atteint 450% de retour sur investissement publicitaire.',
    'portfolio.projects.advertising.author': 'Emma Wilson',
    'portfolio.projects.advertising.position': 'Growth Manager, FitnessFlow',
    
    'portfolio.projects.corporate.title': 'Développement Site Web Corporate',
    'portfolio.projects.corporate.client': 'InnovateTech Solutions',
    'portfolio.projects.corporate.description': 'Site web corporate moderne avec fonctionnalités avancées et expérience utilisateur fluide.',
    'portfolio.projects.corporate.testimonial': 'Le nouveau site web représente parfaitement notre marque et a considérablement augmenté notre génération de leads.',
    'portfolio.projects.corporate.author': 'Alex Thompson',
    'portfolio.projects.corporate.position': 'CTO, InnovateTech',
    
    'portfolio.projects.social.title': 'Stratégie Marketing Réseaux Sociaux',
    'portfolio.projects.social.client': 'BeautyGlow Cosmetics',
    'portfolio.projects.social.description': 'Stratégie complète de réseaux sociaux et création de contenu pour une marque de cosmétiques.',
    'portfolio.projects.social.testimonial': 'Notre présence sur les réseaux sociaux a explosé ! Nous avons gagné 400% de followers en seulement 3 mois.',
    'portfolio.projects.social.author': 'Lisa Park',
    'portfolio.projects.social.position': 'Brand Manager, BeautyGlow',
    
    // About Page
    'aboutPage.title': 'À propos de BTK Agency',
    'aboutPage.subtitle': 'Nous sommes un équipe passionné d\'innovateurs digitaux dédiés à transformer les entreprises grâce à des stratégies innovantes et une technologie de pointe.',
    'aboutPage.values.title': 'Nos Valeurs',
    'aboutPage.stats.title': 'Nos Statistiques',
    'aboutPage.innovation': 'Innovation',
    'aboutPage.innovationDesc': 'Nous restons à l\'avant-garde des tendances et des technologies digitales pour offrir des solutions de pointe.',
    'aboutPage.clientSuccess': 'Succès du Client',
    'aboutPage.clientSuccessDesc': 'Votre succès est notre succès. Nous sommes déterminés à atteindre vos objectifs d\'affaires.',
    'aboutPage.excellence': 'Excellence',
    'aboutPage.excellenceDesc': 'Nous maintenons les plus hauts standards dans chaque projet que nous entreprenons.',
    'aboutPage.collaboration': 'Collaboration',
    'aboutPage.collaborationDesc': 'Nous travaillons étroitement avec nos clients pour nous assurer une alignement et des résultats parfaits.',
    'aboutPage.happyClients': 'Clients Satisfaits',
    'aboutPage.projectsCompleted': 'Projets Réalisés',
    'aboutPage.clientSatisfaction': 'Satisfaction du Client',
    'aboutPage.supportAvailable': 'Support Disponible',
    
    // Case Studies
    'caseStudies.title': 'Études de Cas',
    'caseStudies.subtitle': 'Découvrez comment nous avons aidé nos clients à atteindre des résultats exceptionnels.',
    'caseStudies.filters.all': 'Tous les Études de Cas',
    'caseStudies.filters.ecommerce': 'E-Commerce',
    'caseStudies.filters.saas': 'SaaS',
    'caseStudies.filters.healthcare': 'Santé',
    'caseStudies.filters.finance': 'Finances',
    'caseStudies.viewFullCase': 'Voir l\'Étude Complète',
    'caseStudies.downloadAll': 'Télécharger tous les Études',
    'caseStudies.scheduleConsultation': 'Planifier une Consultation',
    'caseStudies.challenge': 'Défi',
    'caseStudies.solution': 'Solution',
    'caseStudies.results': 'Résultats',
    'caseStudies.process': 'Processus',
    'caseStudies.technologies': 'Technologies',
    'caseStudies.testimonial': 'Témoignage',
    'caseStudies.visitWebsite': 'Visiter le Site Web',
    'caseStudies.duration': 'Durée',
    'caseStudies.industry': 'Secteur',
    
    // Stats
    'stats.caseStudies': 'Études de Cas',
    'stats.successRate': 'Taux de Réussite',
    'stats.revenueGenerated': 'Revenus Générés',
    'stats.supportAvailable': 'Support Disponible',
    'stats.projectsCompleted': 'Projets Réalisés',
    'stats.happyClients': 'Clients Satisfaits',
    'stats.clientSatisfaction': 'Satisfaction Client',
    
    // About Page - Additional sections
    'aboutPage.ourStory.title': 'Notre Histoire',
    'aboutPage.ourStory.paragraph1': 'BTK Agency a été fondée avec une mission simple : aider les entreprises à prospérer dans l\'ère numérique. Nous avons commencé comme une petite équipe de professionnels du marketing et du développement passionnés qui croyaient que chaque entreprise mérite d\'accéder à des solutions digitales de classe mondiale.',
    'aboutPage.ourStory.paragraph2': 'Aujourd\'hui, nous avons grandi pour devenir une agence de services digitaux complète qui sert des clients dans de multiples industries. Notre approche combine pensée stratégique, excellence créative et expertise technique pour livrer des résultats qui dépassent les attentes.',
    'aboutPage.ourStory.paragraph3': 'Nous sommes fiers de notre historique de succès et des relations durables que nous avons construites avec nos clients. Chaque projet est une opportunité de faire une différence et de stimuler une croissance significative.',
    'aboutPage.whyChoose.title': 'Pourquoi Choisir BTK Agency ?',
    'aboutPage.whyChoose.provenTrack': 'Historique de Succès Prouvé',
    'aboutPage.whyChoose.provenTrackDesc': '150+ projets réussis et en croissance',
    'aboutPage.whyChoose.expertTeam': 'Équipe d\'Experts',
    'aboutPage.whyChoose.expertTeamDesc': 'Professionnels certifiés avec des années d\'expérience',
    'aboutPage.whyChoose.customSolutions': 'Solutions Personnalisées',
    'aboutPage.whyChoose.customSolutionsDesc': 'Stratégies adaptées à vos besoins uniques',
    'aboutPage.whyChoose.ongoingSupport': 'Support Continu',
    'aboutPage.whyChoose.ongoingSupportDesc': 'Support 24/7 et services de maintenance',
    'aboutPage.values.subtitle': 'Ces valeurs fondamentales guident tout ce que nous faisons et façonnent la façon dont nous servons nos clients.',
    'aboutPage.team.title': 'Rencontrez Notre Équipe',
    'aboutPage.team.subtitle': 'Les professionnels talentueux derrière le succès de BTK Agency.',
    'aboutPage.mission.title': 'Notre Mission',
    'aboutPage.mission.description1': 'Donner aux entreprises les moyens d\'utiliser des solutions digitales innovantes qui stimulent la croissance, améliorent la présence de marque et livrent des résultats mesurables dans un paysage digital en constante évolution.',
    'aboutPage.mission.description2': 'Nous croyons que chaque entreprise, quelle que soit sa taille, mérite d\'accéder à des services de marketing digital et de technologie de classe mondiale qui peuvent transformer leur présence en ligne et accélérer leur croissance.',
    'aboutPage.vision.title': 'Notre Vision',
    'aboutPage.vision.description1': 'Être l\'agence digitale leader que les entreprises font confiance pour transformer leur présence digitale et atteindre une croissance durable grâce à des stratégies innovantes et une technologie de pointe.',
    'aboutPage.vision.description2': 'Nous envisageons un avenir où chaque entreprise peut exploiter la puissance du marketing digital pour atteindre son plein potentiel et créer des connexions significatives avec son audience.',
    'aboutPage.cta.title': 'Prêt à Travailler Avec Nous ?',
    'aboutPage.cta.subtitle': 'Discutons de la façon dont nous pouvons vous aider à transformer votre entreprise et atteindre vos objectifs digitaux.',
    'aboutPage.cta.button': 'Commencer Avec Nous',
    'aboutPage.founding.text': 'Depuis notre fondation, nous avons aidé des centaines d\'entreprises à atteindre une croissance remarquable et à établir des présences digitales puissantes qui génèrent de vrais résultats.',
    
    // Team Members
    'aboutPage.team.sarah.name': 'Sarah Johnson',
    'aboutPage.team.sarah.position': 'CEO & Fondatrice',
    'aboutPage.team.sarah.bio': '10+ années en marketing digital avec expertise en stratégies de croissance et leadership d\'équipe.',
    'aboutPage.team.sarah.expertise1': 'Planification Stratégique',
    'aboutPage.team.sarah.expertise2': 'Marketing de Croissance',
    'aboutPage.team.sarah.expertise3': 'Leadership d\'Équipe',
    
    'aboutPage.team.michael.name': 'Michael Chen',
    'aboutPage.team.michael.position': 'Directeur Créatif',
    'aboutPage.team.michael.bio': 'Designer primé avec une passion pour créer des expériences de marque mémorables.',
    'aboutPage.team.michael.expertise1': 'Design de Marque',
    'aboutPage.team.michael.expertise2': 'UI/UX',
    'aboutPage.team.michael.expertise3': 'Stratégie Créative',
    
    'aboutPage.team.david.name': 'David Rodriguez',
    'aboutPage.team.david.position': 'Lead Technique',
    'aboutPage.team.david.bio': 'Développeur full-stack avec une expertise approfondie dans les technologies web modernes et l\'architecture.',
    'aboutPage.team.david.expertise1': 'Développement Web',
    'aboutPage.team.david.expertise2': 'Architecture Technique',
    'aboutPage.team.david.expertise3': 'Optimisation Performance',
    
    'aboutPage.team.emma.name': 'Emma Wilson',
    'aboutPage.team.emma.position': 'Directrice Marketing',
    'aboutPage.team.emma.bio': 'Experte en marketing digital spécialisée dans les campagnes basées sur les données et l\'analyse.',
    'aboutPage.team.emma.expertise1': 'Publicité Digitale',
    'aboutPage.team.emma.expertise2': 'Analytics',
    'aboutPage.team.emma.expertise3': 'Stratégie de Campagne',
    
    'aboutPage.team.lisa.name': 'Lisa Park',
    'aboutPage.team.lisa.position': 'Spécialiste SEO',
    'aboutPage.team.lisa.bio': 'Experte SEO avec un historique prouvé d\'amélioration des classements de recherche et du trafic organique.',
    'aboutPage.team.lisa.expertise1': 'Optimisation SEO',
    'aboutPage.team.lisa.expertise2': 'Stratégie de Contenu',
    'aboutPage.team.lisa.expertise3': 'SEO Technique',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    
    // Footer
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Our Services',
    'footer.contact': 'Contact',
    'footer.aboutUs': 'About Us',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.copyright': '© 2025 BTK Agency. All rights reserved.',
    'footer.description': 'Your digital partner to transform your online presence.',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Complete digital solutions to transform your online presence and achieve your business goals.',
    'services.seo.title': 'SEO Optimization',
    'services.seo.description': 'Boost your search rankings and drive organic traffic with our proven SEO strategies.',
    'services.advertising.title': 'Digital Advertising',
    'services.advertising.description': 'Maximize your ROI with targeted advertising campaigns across all major platforms.',
    'services.design.title': 'Brand Design',
    'services.design.description': 'Create a memorable brand identity that resonates with your target audience.',
    'services.web.title': 'Web Development',
    'services.web.description': 'Build fast, responsive websites that convert visitors into customers.',
    'services.analytics.title': 'Analytics Insights',
    'services.analytics.description': 'Turn data into actionable insights to optimize your digital performance.',
    'services.social.title': 'Social Media Marketing',
    'services.social.description': 'Engage your audience and build meaningful connections on social platforms.',
    
    // Hero
    'hero.title': 'Your Digital Growth,Our Expertise',
    'hero.subtitle': 'Transform your brand with cutting-edge digital marketing strategies. We create compelling campaigns that drive results and fuel your business growth.',
    'hero.cta': 'Get Started Today',
    'hero.watchStory': 'Watch Our Story',
    'hero.happyClients': 'Happy Clients',
    'hero.projectsCompleted': 'Projects Completed',
    'hero.successRate': 'Success Rate',
    'hero.support': 'Support',
    
    // About
    'about.title': 'About BTK Agency',
    'about.subtitle': 'We are a forward-thinking digital marketing agency dedicated to transforming businesses through innovative strategies and cutting-edge technology.',
    'about.learnStory': 'Learn Our Story',
    'about.happyClients': 'Happy Clients',
    'about.projectsCompleted': 'Projects Completed',
    'about.successRate': 'Success Rate',
    'about.yearsExperience': 'Years Experience',
    'about.innovationFirst': 'Innovation First',
    'about.innovationFirstDesc': 'We stay ahead of digital trends to deliver cutting-edge solutions that give you a competitive advantage.',
    'about.resultsDriven': 'Results-Driven',
    'about.resultsDrivenDesc': 'Every strategy we implement is designed to deliver measurable results and maximize your return on investment.',
    'about.clientPartnership': 'Client Partnership',
    'about.clientPartnershipDesc': 'We believe in building long-term partnerships, working closely with you to understand and achieve your goals.',
    'about.transparentProcess': 'Transparent Process',
    'about.transparentProcessDesc': 'Complete transparency in our processes, pricing, and results. You\'ll always know exactly what we\'re doing and why.',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Ready to transform your business? Let\'s talk!',
    'contact.email.title': 'Email Us',
    'contact.email.description': 'Send us an email anytime',
    'contact.phone.title': 'Call Us',
    'contact.phone.description': 'Mon-Fri from 8am to 6pm',
    'contact.address.title': 'Visit Us',
    'contact.hours.title': 'Working Hours',
    'contact.hours.days': 'Monday - Friday',
    'contact.hours.time': '8:00 AM - 6:00 PM GMT+1',
    'contact.form.name': 'Name',
    'contact.form.namePlaceholder': 'Your name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'How can we help?',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Tell us about your project...',
    'contact.form.send': 'Send Message',
    
    // Common
    'learnMore': 'Learn More',
    'getStarted': 'Get Started',
    'contactUs': 'Contact Us',
    'language': 'Language',
    
    // Portfolio
    'portfolio.title': 'Our Portfolio',
    'portfolio.subtitle': 'Discover our most outstanding projects and the impact we\'ve created for our clients.',
    'portfolio.filters.all': 'All Projects',
    'portfolio.filters.web': 'Web Development',
    'portfolio.filters.branding': 'Branding',
    'portfolio.filters.marketing': 'Digital Marketing',
    'portfolio.filters.seo': 'SEO',
    'portfolio.viewProject': 'View Project',
    'portfolio.technologies': 'Technologies',
    'portfolio.results': 'Results',
    'portfolio.testimonial': 'Testimonial',
    'portfolio.loadMore': 'Load More Projects',
    'portfolio.downloadPDF': 'Download Portfolio PDF',
    
    // Portfolio Projects
    'portfolio.projects.ecommerce.title': 'E-Commerce Platform Redesign',
    'portfolio.projects.ecommerce.client': 'TechCorp Inc.',
    'portfolio.projects.ecommerce.description': 'Complete redesign and development of a modern e-commerce platform with enhanced user experience and increased conversion rates.',
    'portfolio.projects.ecommerce.testimonial': 'BTK Agency transformed our online presence completely. The new platform increased our sales by 120% in just 6 months.',
    'portfolio.projects.ecommerce.author': 'Sarah Johnson',
    'portfolio.projects.ecommerce.position': 'CEO, TechCorp Inc.',
    
    'portfolio.projects.branding.title': 'Brand Identity & Marketing Campaign',
    'portfolio.projects.branding.client': 'GreenLife Organics',
    'portfolio.projects.branding.description': 'Comprehensive brand identity design and digital marketing campaign for an organic food company.',
    'portfolio.projects.branding.testimonial': 'The brand transformation exceeded our expectations. Our social media engagement increased by 150%.',
    'portfolio.projects.branding.author': 'Michael Chen',
    'portfolio.projects.branding.position': 'Marketing Director, GreenLife',
    
    'portfolio.projects.seo.title': 'SEO Optimization & Content Strategy',
    'portfolio.projects.seo.client': 'LegalAdvice Pro',
    'portfolio.projects.seo.description': 'Comprehensive SEO strategy and content optimization for a legal services website.',
    'portfolio.projects.seo.testimonial': 'Our organic traffic increased by 200% and we\'re now ranking for all our target keywords.',
    'portfolio.projects.seo.author': 'David Rodriguez',
    'portfolio.projects.seo.position': 'Founder, LegalAdvice Pro',
    
    'portfolio.projects.advertising.title': 'Digital Advertising Campaign',
    'portfolio.projects.advertising.client': 'FitnessFlow',
    'portfolio.projects.advertising.description': 'Multi-channel digital advertising campaign for a fitness app with targeted audience segmentation.',
    'portfolio.projects.advertising.testimonial': 'The campaign delivered exceptional ROI. We achieved 450% return on ad spend.',
    'portfolio.projects.advertising.author': 'Emma Wilson',
    'portfolio.projects.advertising.position': 'Growth Manager, FitnessFlow',
    
    'portfolio.projects.corporate.title': 'Corporate Website Development',
    'portfolio.projects.corporate.client': 'InnovateTech Solutions',
    'portfolio.projects.corporate.description': 'Modern corporate website with advanced features and seamless user experience.',
    'portfolio.projects.corporate.testimonial': 'The new website perfectly represents our brand and has significantly increased our lead generation.',
    'portfolio.projects.corporate.author': 'Alex Thompson',
    'portfolio.projects.corporate.position': 'CTO, InnovateTech',
    
    'portfolio.projects.social.title': 'Social Media Marketing Strategy',
    'portfolio.projects.social.client': 'BeautyGlow Cosmetics',
    'portfolio.projects.social.description': 'Comprehensive social media strategy and content creation for a cosmetics brand.',
    'portfolio.projects.social.testimonial': 'Our social media presence exploded! We gained 400% more followers in just 3 months.',
    'portfolio.projects.social.author': 'Lisa Park',
    'portfolio.projects.social.position': 'Brand Manager, BeautyGlow',
    
    // About Page
    'aboutPage.title': 'About BTK Agency',
    'aboutPage.subtitle': 'We are a passionate team of digital innovators dedicated to transforming businesses through innovative strategies and cutting-edge technology.',
    'aboutPage.values.title': 'Our Values',
    'aboutPage.team.title': 'Our Team',
    'aboutPage.stats.title': 'Our Statistics',
    'aboutPage.innovation': 'Innovation',
    'aboutPage.innovationDesc': 'We stay at the forefront of digital trends and technologies to offer cutting-edge solutions.',
    'aboutPage.clientSuccess': 'Client Success',
    'aboutPage.clientSuccessDesc': 'Your success is our success. We are committed to achieving your business objectives.',
    'aboutPage.excellence': 'Excellence',
    'aboutPage.excellenceDesc': 'We maintain the highest standards in every project we undertake.',
    'aboutPage.collaboration': 'Collaboration',
    'aboutPage.collaborationDesc': 'We work closely with our clients to ensure alignment and perfect results.',
    'aboutPage.happyClients': 'Happy Clients',
    'aboutPage.projectsCompleted': 'Projects Completed',
    'aboutPage.clientSatisfaction': 'Client Satisfaction',
    'aboutPage.supportAvailable': 'Support Available',
    
    // Case Studies
    'caseStudies.title': 'Case Studies',
    'caseStudies.subtitle': 'Discover how we\'ve helped our clients achieve exceptional results.',
    'caseStudies.filters.all': 'All Case Studies',
    'caseStudies.filters.ecommerce': 'E-Commerce',
    'caseStudies.filters.saas': 'SaaS',
    'caseStudies.filters.healthcare': 'Healthcare',
    'caseStudies.filters.finance': 'Finance',
    'caseStudies.viewFullCase': 'View Full Case Study',
    'caseStudies.downloadAll': 'Download All Case Studies',
    'caseStudies.scheduleConsultation': 'Schedule Consultation',
    'caseStudies.challenge': 'Challenge',
    'caseStudies.solution': 'Solution',
    'caseStudies.results': 'Results',
    'caseStudies.process': 'Process',
    'caseStudies.technologies': 'Technologies',
    'caseStudies.testimonial': 'Testimonial',
    'caseStudies.visitWebsite': 'Visit Website',
    'caseStudies.duration': 'Duration',
    'caseStudies.industry': 'Industry',
    
    // Stats
    'stats.caseStudies': 'Case Studies',
    'stats.successRate': 'Success Rate',
    'stats.revenueGenerated': 'Revenue Generated',
    'stats.supportAvailable': 'Support Available',
    'stats.projectsCompleted': 'Projects Completed',
    'stats.happyClients': 'Happy Clients',
    'stats.clientSatisfaction': 'Client Satisfaction',
    
    // About Page - Additional
    'aboutPage.ourStory': 'Our Story',
    'aboutPage.ourStoryDesc1': 'BTK Agency was founded with a simple mission: to help businesses thrive in the digital age. We started as a small team of marketing and development professionals who believed that every business deserves access to world-class digital solutions.',
    'aboutPage.ourStoryDesc2': 'Today, we have grown to become a complete digital services agency serving clients across multiple industries. Our approach combines strategic thinking, creative excellence, and technical expertise to deliver results that exceed expectations.',
    'aboutPage.ourStoryDesc3': 'We are proud of our track record of success and the lasting relationships we have built with our clients. Every project is an opportunity to make a difference and drive significant growth.',
    'aboutPage.whyChooseUs': 'Why Choose BTK Agency?',
    'aboutPage.provenTrackRecord': 'Proven Track Record',
    'aboutPage.provenTrackRecordDesc': '150+ successful projects and growing',
    'aboutPage.expertTeam': 'Expert Team',
    'aboutPage.expertTeamDesc': 'Certified professionals with years of experience',
    'aboutPage.customSolutions': 'Custom Solutions',
    'aboutPage.customSolutionsDesc': 'Strategies tailored to your unique needs',
    'aboutPage.ongoingSupport': 'Ongoing Support',
    'aboutPage.ongoingSupportDesc': '24/7 support and maintenance services',
    'aboutPage.ourValues': 'Our Values',
    'aboutPage.ourValuesDesc': 'These core values guide everything we do and shape how we serve our clients.',
    'aboutPage.ourTeam': 'Our Team',
    'aboutPage.ourTeamDesc': 'Meet the passionate experts who make BTK Agency a top-tier agency.',
    
    // About Page - Complete translations
    'aboutPage.founding.text': 'Founded in 2020, we have been helping businesses grow and thrive in the digital world.',
    'aboutPage.ourStory.title': 'Our Story',
    'aboutPage.ourStory.paragraph1': 'BTK Agency was founded with a simple mission: to help businesses thrive in the digital age. We started as a small team of marketing and development professionals who believed that every business deserves access to world-class digital solutions.',
    'aboutPage.ourStory.paragraph2': 'Today, we have grown to become a complete digital services agency serving clients across multiple industries. Our approach combines strategic thinking, creative excellence, and technical expertise to deliver results that exceed expectations.',
    'aboutPage.ourStory.paragraph3': 'We are proud of our track record of success and the lasting relationships we have built with our clients. Every project is an opportunity to make a difference and drive significant growth.',
    'aboutPage.whyChoose.title': 'Why Choose BTK Agency?',
    'aboutPage.whyChoose.provenTrack': 'Proven Track Record',
    'aboutPage.whyChoose.provenTrackDesc': '150+ successful projects and growing',
    'aboutPage.whyChoose.expertTeam': 'Expert Team',
    'aboutPage.whyChoose.expertTeamDesc': 'Certified professionals with years of experience',
    'aboutPage.whyChoose.customSolutions': 'Custom Solutions',
    'aboutPage.whyChoose.customSolutionsDesc': 'Strategies tailored to your unique needs',
    'aboutPage.whyChoose.ongoingSupport': 'Ongoing Support',
    'aboutPage.whyChoose.ongoingSupportDesc': '24/7 support and maintenance services',
    'aboutPage.values.subtitle': 'These core values guide everything we do and shape how we serve our clients.',
    'aboutPage.team.subtitle': 'Meet the passionate experts who make BTK Agency a top-tier agency.',
    'aboutPage.team.sarah.name': 'Sarah Johnson',
    'aboutPage.team.sarah.position': 'CEO & Founder',
    'aboutPage.team.sarah.bio': 'Digital visionary with 10+ years of experience in business transformation.',
    'aboutPage.team.sarah.expertise1': 'Digital Strategy',
    'aboutPage.team.sarah.expertise2': 'Leadership',
    'aboutPage.team.sarah.expertise3': 'Innovation',
    'aboutPage.team.michael.name': 'Michael Chen',
    'aboutPage.team.michael.position': 'CTO',
    'aboutPage.team.michael.bio': 'Expert in web development and scalable system architecture.',
    'aboutPage.team.michael.expertise1': 'Web Development',
    'aboutPage.team.michael.expertise2': 'Architecture',
    'aboutPage.team.michael.expertise3': 'DevOps',
    'aboutPage.team.david.name': 'David Rodriguez',
    'aboutPage.team.david.position': 'Marketing Director',
    'aboutPage.team.david.bio': 'Digital marketing strategist specialized in business growth.',
    'aboutPage.team.david.expertise1': 'Digital Marketing',
    'aboutPage.team.david.expertise2': 'SEO',
    'aboutPage.team.david.expertise3': 'Analytics',
    'aboutPage.team.emma.name': 'Emma Thompson',
    'aboutPage.team.emma.position': 'Senior Designer',
    'aboutPage.team.emma.bio': 'Creative designer passionate about creating impactful visual experiences.',
    'aboutPage.team.emma.expertise1': 'UI/UX Design',
    'aboutPage.team.emma.expertise2': 'Branding',
    'aboutPage.team.emma.expertise3': 'Illustration',
    'aboutPage.team.lisa.name': 'Lisa Wang',
    'aboutPage.team.lisa.position': 'Content Specialist',
    'aboutPage.team.lisa.bio': 'Strategic content creator who connects brands with audiences.',
    'aboutPage.team.lisa.expertise1': 'Content Strategy',
    'aboutPage.team.lisa.expertise2': 'Copywriting',
    'aboutPage.team.lisa.expertise3': 'Social Media',
    'aboutPage.mission.title': 'Our Mission',
    'aboutPage.mission.description1': 'Our mission is to empower businesses with innovative digital solutions that drive growth and transformation. We believe that every business, regardless of size, deserves access to cutting-edge technology and effective marketing strategies.',
    'aboutPage.mission.description2': 'We strive to be the trusted digital partner our clients need to navigate today\'s complex digital landscape and build a prosperous future.',
    'aboutPage.vision.title': 'Our Vision',
    'aboutPage.vision.description1': 'We envision a future where every business has the digital tools and strategies needed to reach their full potential. We want to be recognized as the agency that transforms not only our clients\' digital presence, but also their impact on the world.',
    'aboutPage.vision.description2': 'Our vision is to create a digital ecosystem where innovation, creativity, and results come together to create lasting and meaningful impact.',
    'aboutPage.cta.title': 'Ready to Transform Your Business?',
    'aboutPage.cta.subtitle': 'Join hundreds of businesses that have already experienced the power of our digital solutions.',
    'aboutPage.cta.button': 'Get Quote',
    'aboutPage.ourStoryDesc1': 'BTK Agency was founded with a simple mission: to help businesses thrive in the digital era. We started as a small team of passionate marketers and developers who believed that every business deserves access to world-class digital solutions.',
    'aboutPage.ourStoryDesc2': 'Today, we have grown to become a full-service digital agency serving clients across multiple industries. Our approach combines strategic thinking, creative excellence, and technical expertise to deliver results that exceed expectations.',
    'aboutPage.ourStoryDesc3': 'We are proud of our proven track record and the lasting relationships we have built with our clients. Each project is an opportunity to make a difference and stimulate significant growth.',
    'aboutPage.whyChooseUs': 'Why Choose BTK Agency ?',
    'aboutPage.provenTrackRecord': 'Proven Track Record',
    'aboutPage.provenTrackRecordDesc': '150+ successful projects and growing',
    'aboutPage.expertTeam': 'Expert Team',
    'aboutPage.expertTeamDesc': 'Certified professionals with years of experience',
    'aboutPage.customSolutions': 'Custom Solutions',
    'aboutPage.customSolutionsDesc': 'Strategies tailored to your unique needs',
    'aboutPage.ongoingSupport': 'Ongoing Support',
    'aboutPage.ongoingSupportDesc': '24/7 support and maintenance services',
    'aboutPage.ourValues': 'Our Values',
    'aboutPage.ourValuesDesc': 'These fundamental values guide everything we do and shape the way we serve our clients.',
    'aboutPage.ourTeam': 'Our Team',
    'aboutPage.ourTeamDesc': 'Meet the passionate experts who make BTK Agency a top agency.',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.portfolio': 'الأعمال',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    
    // Footer
    'footer.quickLinks': 'روابط سريعة',
    'footer.services': 'خدماتنا',
    'footer.contact': 'اتصل بنا',
    'footer.aboutUs': 'من نحن',
    'footer.terms': 'شروط الخدمة',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.copyright': '© 2024 وكالة BTK. جميع الحقوق محفوظة.',
    'footer.description': 'شريكك الرقمي لتحويل وجودك عبر الإنترنت.',
    
    // Services
    'services.title': 'خدماتنا',
    'services.subtitle': 'حلول رقمية شاملة لتحويل وجودك عبر الإنترنت وتحقيق أهداف عملك.',
    'services.seo.title': 'تحسين محركات البحث',
    'services.seo.description': 'عزز ترتيبك في محركات البحث وادفع حركة مرور عضوية باستراتيجيات SEO المثبتة.',
    'services.advertising.title': 'الإعلان الرقمي',
    'services.advertising.description': 'احصل على أقصى عائد استثمار مع حملات إعلانية مستهدفة عبر جميع المنصات الرئيسية.',
    'services.design.title': 'تصميم العلامة التجارية',
    'services.design.description': 'أنشئ هوية علامة تجارية لا تُنسى تتردد صداها مع جمهورك المستهدف.',
    'services.web.title': 'تطوير الويب',
    'services.web.description': 'أنشئ مواقع ويب سريعة ومتجاوبة تحول الزوار إلى عملاء.',
    'services.analytics.title': 'تحليلات ورؤى',
    'services.analytics.description': 'حول البيانات إلى رؤى قابلة للتنفيذ لتحسين أدائك الرقمي.',
    'services.social.title': 'التسويق عبر وسائل التواصل الاجتماعي',
    'services.social.description': 'انخرط مع جمهورك وابني روابط هادفة على المنصات الاجتماعية.',
    
    // Hero
    'hero.title': 'نموك الرقمي,خبرتنا',
    'hero.subtitle': 'حول علامتك التجارية باستراتيجيات التسويق الرقمي المتطورة. ننشئ حملات مقنعة تحقق النتائج وتدفع نمو عملك.',
    'hero.cta': 'ابدأ اليوم',
    'hero.watchStory': 'شاهد قصتنا',
    'hero.happyClients': 'عملاء سعداء',
    'hero.projectsCompleted': 'مشاريع مكتملة',
    'hero.successRate': 'معدل النجاح',
    'hero.support': 'الدعم',
    
    // About
    'about.title': 'من نحن وكالة BTK',
    'about.subtitle': 'نحن وكالة تسويق رقمي متقدمة مكرسة لتحويل الشركات من خلال استراتيجيات مبتكرة وتكنولوجيا متطورة.',
    'about.learnStory': 'تعرف على قصتنا',
    'about.happyClients': 'عملاء سعداء',
    'about.projectsCompleted': 'مشاريع مكتملة',
    'about.successRate': 'معدل النجاح',
    'about.yearsExperience': 'سنوات الخبرة',
    'about.innovationFirst': 'الابتكار الأول',
    'about.innovationFirstDesc': 'نحن نبقى أمام الاتجاهات الرقمية لتقديم حلول متطورة يعطيك ميزة تنافسية.',
    'about.resultsDriven': 'مركز على النتائج',
    'about.resultsDrivenDesc': 'كل استراتيجية ننفذها مصممة لتوفير نتائج قابلة للقياس وتعظيم عائد استثمارك.',
    'about.clientPartnership': 'شراكة العميل',
    'about.clientPartnershipDesc': 'نؤمن ببناء شراكات طويلة المدى، عمل معك بشكل وثيق لفهم وتحقيق أهدافك.',
    'about.transparentProcess': 'عملية شفافة',
    'about.transparentProcessDesc': 'شفافية كاملة في عملياتنا وأسعارنا والنتائج. ستعرف دائماً بالضبط ما نقوم به ولماذا.',
    
    // Contact
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'مستعد لتحويل عملك؟ دعنا نتحدث!',
    'contact.email.title': 'راسلنا عبر البريد الإلكتروني',
    'contact.email.description': 'أرسل لنا بريد إلكتروني في أي وقت',
    'contact.phone.title': 'اتصل بنا',
    'contact.phone.description': 'الاثنين-الجمعة من 8 صباحاً إلى 6 مساءً',
    'contact.address.title': 'زرنا',
    'contact.hours.title': 'ساعات العمل',
    'contact.hours.days': 'الاثنين - الجمعة',
    'contact.hours.time': '8:00 صباحاً - 6:00 مساءً GMT+1',
    'contact.form.name': 'الاسم',
    'contact.form.namePlaceholder': 'اسمك',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.subject': 'الموضوع',
    'contact.form.subjectPlaceholder': 'كيف يمكننا مساعدتك؟',
    'contact.form.message': 'الرسالة',
    'contact.form.messagePlaceholder': 'أخبرنا عن مشروعك...',
    'contact.form.send': 'إرسال الرسالة',
    
    // Common
    'learnMore': 'اعرف المزيد',
    'getStarted': 'ابدأ',
    'contactUs': 'اتصل بنا',
    'language': 'اللغة',
    
    // Portfolio
    'portfolio.title': 'الأعمال',
    'portfolio.subtitle': 'اكتشف أعمالنا الأكثر إثارة والتأثير الذي أنشأناه لعملائنا.',
    'portfolio.filters.all': 'جميع المشاريع',
    'portfolio.filters.web': 'تطوير الويب',
    'portfolio.filters.branding': 'تصميم العلامة التجارية',
    'portfolio.filters.marketing': 'التسويق عبر الوسائل الاجتماعية',
    'portfolio.filters.seo': 'SEO',
    'portfolio.viewProject': 'عرض المشروع',
    'portfolio.technologies': 'التكنولوجيات',
    'portfolio.results': 'النتائج',
    'portfolio.testimonial': 'التعليقات',
    'portfolio.loadMore': 'تحميل المزيد من المشاريع',
    
    // About Page
    'aboutPage.title': 'من نحن وكالة BTK',
    'aboutPage.subtitle': 'نحن فريق متحمس من المبتكرين الرقميين المكرسين لتحويل الشركات من خلال استراتيجيات مبتكرة وتكنولوجيا متطورة.',
    'aboutPage.values.title': 'قيمنا',
    'aboutPage.team.title': 'فريقنا',
    'aboutPage.stats.title': 'الإحصائيات',
    'aboutPage.innovation': 'الابتكار',
    'aboutPage.innovationDesc': 'نحن نبقى أمام الاتجاهات الرقمية والتكنولوجيا لتقديم حلول متطورة.',
    'aboutPage.clientSuccess': 'نجاح العميل',
    'aboutPage.clientSuccessDesc': 'نجاحك هو نجاحنا. نحن ملتزمون بتحقيق أهداف عملك التجارية.',
    'aboutPage.excellence': 'التميز',
    'aboutPage.excellenceDesc': 'نحن نحافظ على أعلى المعايير في كل مشروع نقوم به.',
    'aboutPage.collaboration': 'التعاون',
    'aboutPage.collaborationDesc': 'نعمل بشكل وثيق مع عملائنا لضمان التوافق والنتائج المثالية.',
    'aboutPage.happyClients': 'عملاء سعداء',
    'aboutPage.projectsCompleted': 'مشاريع مكتملة',
    'aboutPage.clientSatisfaction': 'الرضا عن العميل',
    'aboutPage.supportAvailable': 'الدعم متاح',
    
    // Case Studies
    'caseStudies.title': 'دراسات الحالة',
    'caseStudies.subtitle': 'اكتشف كيف ساعدنا عملائنا في تحقيق نتائج متفوقة.',
    'caseStudies.filters.all': 'جميع دراسات الحالة',
    'caseStudies.filters.ecommerce': 'التجارة الإلكترونية',
    'caseStudies.filters.saas': 'SaaS',
    'caseStudies.filters.healthcare': 'الصحة',
    'caseStudies.filters.finance': 'المالية',
    'caseStudies.viewFullCase': 'عرض دراسة حالة كاملة',
    'caseStudies.downloadAll': 'تحميل جميع دراسات الحالة',
    'caseStudies.scheduleConsultation': 'احجز موعداً',
    'caseStudies.challenge': 'التحدي',
    'caseStudies.solution': 'الحل',
    'caseStudies.results': 'النتائج',
    'caseStudies.process': 'العملية',
    'caseStudies.technologies': 'التكنولوجيات',
    'caseStudies.testimonial': 'التعليقات',
    'caseStudies.visitWebsite': 'زيارة الموقع',
    'caseStudies.duration': 'المدة',
    'caseStudies.industry': 'القطاع',
    
    // Stats
    'stats.caseStudies': 'دراسات الحالة',
    'stats.successRate': 'معدل النجاح',
    'stats.revenueGenerated': 'الإيرادات المولدة',
    'stats.supportAvailable': 'الدعم متاح',
    'stats.projectsCompleted': 'المشاريع المكتملة',
    'stats.happyClients': 'العملاء السعداء',
    'stats.clientSatisfaction': 'الرضا عن العميل',
    
    // About Page - Additional
    'aboutPage.ourStory': 'قصتنا',
    'aboutPage.ourStoryDesc1': 'تم إنشاء وكالة BTK بهدف واحد فقط: مساعدة الشركات على النمو في العصر الرقمي. بدأنا كفريق صغير من المترجمين والمطورين المهتمين بالتسويق الذين يؤمنون بأن كل شركة يستحق أن تتمتع بوصول إلى حلول رقمية من صنع عالمي.',
    'aboutPage.ourStoryDesc2': 'اليوم، نمت إلى أن نصبح وكالة خدمات رقمية كاملة تقدم خدماتها لعملاء في صناعات متعددة. أسلوبنا يجمع بين التفكير الاستراتيجي، الإبداع الرائع، والخبرة الفنية لتقديم نتائج تتجاوز التوقعات.',
    'aboutPage.ourStoryDesc3': 'نحن فخورون بسجل النجاح والعلاقات المستمرة التي بنيناها مع عملائنا. كل مشروع هو فرصة لإجراء فرقة وتحفيز نموًا إيجابيًا كبيرًا.',
    'aboutPage.whyChooseUs': 'لماذا اختر BTK Agency ؟',
    'aboutPage.provenTrackRecord': 'سجل نجاح مثبت',
    'aboutPage.provenTrackRecordDesc': '150+ مشروع ناجح وينمو',
    'aboutPage.expertTeam': 'فريق الخبراء',
    'aboutPage.expertTeamDesc': 'محترفون معتمدون مع سنوات من الخبرة',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.portfolio': 'Portfolio',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    
    // Footer
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.services': 'Nuestros Servicios',
    'footer.contact': 'Contacto',
    'footer.aboutUs': 'Acerca de Nosotros',
    'footer.terms': 'Términos de Servicio',
    'footer.privacy': 'Política de Privacidad',
    'footer.copyright': '© 2025 BTK Agency. Todos los derechos reservados.',
    'footer.description': 'Tu socio digital para transformar tu presencia en línea.',
    
    // Services
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Soluciones digitales completas para transformar tu presencia en línea y alcanzar tus objetivos empresariales.',
    'services.seo.title': 'Optimización SEO',
    'services.seo.description': 'Impulsa tu posicionamiento en buscadores y genera tráfico orgánico con nuestras estrategias SEO probadas.',
    'services.advertising.title': 'Publicidad Digital',
    'services.advertising.description': 'Maximiza tu ROI con campañas publicitarias dirigidas en todas las plataformas principales.',
    'services.design.title': 'Diseño de Marca',
    'services.design.description': 'Crea una identidad de marca memorable que resuene con tu audiencia objetivo.',
    'services.web.title': 'Desarrollo Web',
    'services.web.description': 'Construye sitios web rápidos y responsivos que conviertan visitantes en clientes.',
    'services.analytics.title': 'Análisis e Insights',
    'services.analytics.description': 'Convierte datos en insights accionables para optimizar tu rendimiento digital.',
    'services.social.title': 'Marketing en Redes Sociales',
    'services.social.description': 'Engancha a tu audiencia y construye conexiones significativas en plataformas sociales.',
    
    // Hero
    'hero.title': 'Tu Crecimiento Digital,Nuestra Experiencia',
    'hero.subtitle': 'Transforma tu marca con estrategias de marketing digital de vanguardia. Creamos campañas convincentes que generan resultados e impulsan el crecimiento de tu negocio.',
    'hero.cta': 'Comenzar Hoy',
    'hero.watchStory': 'Ver Nuestra Historia',
    'hero.happyClients': 'Clientes Felices',
    'hero.projectsCompleted': 'Proyectos Completados',
    'hero.successRate': 'Tasa de Éxito',
    'hero.support': 'Soporte',
    
    // About
    'about.title': 'Acerca de BTK Agency',
    'about.subtitle': 'Somos una agencia de marketing digital visionaria dedicada a transformar empresas a través de estrategias innovadoras y tecnología de vanguardia.',
    'about.learnStory': 'Conoce Nuestra Historia',
    'about.happyClients': 'Clientes Felices',
    'about.projectsCompleted': 'Proyectos Completados',
    'about.successRate': 'Tasa de Éxito',
    'about.yearsExperience': 'Años de Experiencia',
    'about.innovationFirst': 'Innovación Primero',
    'about.innovationFirstDesc': 'Nos mantenemos a la vanguardia de las tendencias digitales para ofrecer soluciones de vanguardia que te dan una ventaja competitiva.',
    'about.resultsDriven': 'Orientado a Resultados',
    'about.resultsDrivenDesc': 'Cada estrategia que implementamos está diseñada para entregar resultados medibles y maximizar tu retorno de inversión.',
    'about.clientPartnership': 'Partnership de Clientes',
    'about.clientPartnershipDesc': 'Creemos en la construcción de partners de largo plazo, trabajando estrechamente contigo para comprender y lograr tus objetivos.',
    'about.transparentProcess': 'Proceso Transparente',
    'about.transparentProcessDesc': 'Transparencia completa en nuestros procesos, precios y resultados. Siempre sabrás exactamente qué estamos haciendo y por qué.',
    
    // Contact
    'contact.title': 'Contáctanos',
    'contact.subtitle': '¿Listo para transformar tu negocio? ¡Hablemos!',
    'contact.email.title': 'Envíanos un Email',
    'contact.email.description': 'Envíanos un email en cualquier momento',
    'contact.phone.title': 'Llámanos',
    'contact.phone.description': 'Lun-Vie de 8am a 6pm',
    'contact.address.title': 'Visítanos',
    'contact.hours.title': 'Horario de Trabajo',
    'contact.hours.days': 'Lunes - Viernes',
    'contact.hours.time': '8:00 AM - 6:00 PM GMT+1',
    'contact.form.name': 'Nombre',
    'contact.form.namePlaceholder': 'Tu nombre',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'tu@email.com',
    'contact.form.subject': 'Asunto',
    'contact.form.subjectPlaceholder': '¿Cómo podemos ayudarte?',
    'contact.form.message': 'Mensaje',
    'contact.form.messagePlaceholder': 'Cuéntanos sobre tu proyecto...',
    'contact.form.send': 'Enviar Mensaje',
    
    // Common
    'learnMore': 'Saber Más',
    'getStarted': 'Comenzar',
    'contactUs': 'Contáctanos',
    'language': 'Idioma',
    
    // Portfolio
    'portfolio.title': 'Nuestro Portfolio',
    'portfolio.subtitle': 'Descubre nuestros proyectos más destacados y el impacto que hemos creado para nuestros clientes.',
    'portfolio.filters.all': 'Todos los Proyectos',
    'portfolio.filters.web': 'Desarrollo Web',
    'portfolio.filters.branding': 'Diseño de Marca',
    'portfolio.filters.marketing': 'Marketing Digital',
    'portfolio.filters.seo': 'SEO',
    'portfolio.viewProject': 'Ver Proyecto',
    'portfolio.technologies': 'Tecnologías',
    'portfolio.results': 'Resultados',
    'portfolio.testimonial': 'Testimonio',
    'portfolio.loadMore': 'Cargar Más Proyectos',
    
    // About Page
    'aboutPage.title': 'Acerca de BTK Agency',
    'aboutPage.subtitle': 'Somos un equipo apasionado de innovadores digitales dedicados a transformar empresas a través de estrategias innovadoras y tecnología de vanguardia.',
    'aboutPage.values.title': 'Nuestros Valores',
    'aboutPage.team.title': 'Nuestro Equipo',
    'aboutPage.stats.title': 'Nuestras Estadísticas',
    'aboutPage.innovation': 'Innovación',
    'aboutPage.innovationDesc': 'Nos mantenemos a la vanguardia de las tendencias digitales para ofrecer soluciones de vanguardia que te dan una ventaja competitiva.',
    'aboutPage.clientSuccess': 'Éxito del Cliente',
    'aboutPage.clientSuccessDesc': 'Tu éxito es nuestro éxito. Estamos comprometidos a lograr tus objetivos empresariales.',
    'aboutPage.excellence': 'Excelencia',
    'aboutPage.excellenceDesc': 'Mantenemos los más altos estándares en cada proyecto que emprendemos.',
    'aboutPage.collaboration': 'Colaboración',
    'aboutPage.collaborationDesc': 'Trabajamos estrechamente con nuestros clientes para asegurar una alineación y resultados perfectos.',
    'aboutPage.happyClients': 'Clientes Felices',
    'aboutPage.projectsCompleted': 'Proyectos Completados',
    'aboutPage.clientSatisfaction': 'Satisfacción del Cliente',
    'aboutPage.supportAvailable': 'Soporte Disponible',
    
    // Case Studies
    'caseStudies.title': 'Estudios de Caso',
    'caseStudies.subtitle': 'Descubre cómo hemos ayudado a nuestros clientes a lograr resultados excepcionales.',
    'caseStudies.filters.all': 'Todos los Estudios de Caso',
    'caseStudies.filters.ecommerce': 'E-Commerce',
    'caseStudies.filters.saas': 'SaaS',
    'caseStudies.filters.healthcare': 'Salud',
    'caseStudies.filters.finance': 'Finanzas',
    'caseStudies.viewFullCase': 'Ver Estudio Completo',
    'caseStudies.downloadAll': 'Descargar Todos los Estudios',
    'caseStudies.scheduleConsultation': 'Programar Consulta',
    'caseStudies.challenge': 'Desafío',
    'caseStudies.solution': 'Solución',
    'caseStudies.results': 'Resultados',
    'caseStudies.process': 'Proceso',
    'caseStudies.technologies': 'Tecnologías',
    'caseStudies.testimonial': 'Testimonio',
    'caseStudies.visitWebsite': 'Visitar Sitio Web',
    'caseStudies.duration': 'Duración',
    'caseStudies.industry': 'Industria',
    
    // Stats
    'stats.caseStudies': 'Estudios de Caso',
    'stats.successRate': 'Tasa de Éxito',
    'stats.revenueGenerated': 'Ingresos Generados',
    'stats.supportAvailable': 'Soporte Disponible',
    'stats.projectsCompleted': 'Proyectos Completados',
    'stats.happyClients': 'Clientes Felices',
    'stats.clientSatisfaction': 'Satisfacción del Cliente',
    
    // About Page - Additional
    'aboutPage.ourStory': 'Nuestra Historia',
    'aboutPage.ourStoryDesc1': 'BTK Agency fue fundada con una misión simple: ayudar a las empresas a prosperar en la era digital. Comenzamos como un pequeño equipo de profesionales de marketing y desarrollo que creían que cada empresa merece acceso a soluciones digitales de clase mundial.',
    'aboutPage.ourStoryDesc2': 'Hoy, hemos crecido para convertirnos en una agencia de servicios digitales completa que ofrece sus servicios a clientes en múltiples industrias. Nuestro enfoque combina pensamiento estratégico, excelencia creativa y experiencia técnica para entregar resultados que superan las expectativas.',
    'aboutPage.ourStoryDesc3': 'Estamos orgullosos de nuestro historial de éxito y las relaciones duraderas que hemos construido con nuestros clientes. Cada proyecto es una oportunidad para hacer una diferencia y estimular un crecimiento significativo.',
    'aboutPage.whyChooseUs': '¿Por qué elegir BTK Agency ?',
    'aboutPage.provenTrackRecord': 'Registro de Éxito Proveniente',
    'aboutPage.provenTrackRecordDesc': '150+ proyectos exitosos y creciendo',
    'aboutPage.expertTeam': 'Equipo de Expertos',
    'aboutPage.expertTeamDesc': 'Profesionales certificados con años de experiencia',
    'aboutPage.customSolutions': 'Soluciones Personalizadas',
    'aboutPage.customSolutionsDesc': 'Estrategias adaptadas a sus necesidades únicas',
    'aboutPage.ongoingSupport': 'Soporte Continuo',
    'aboutPage.ongoingSupportDesc': 'Soporte 24/7 y servicios de mantenimiento',
    'aboutPage.ourValues': 'Nuestros Valores',
    'aboutPage.ourValuesDesc': 'Estos valores fundamentales guían todo lo que hacemos y forman la manera en que servimos a nuestros clientes.',
    'aboutPage.ourTeam': 'Nuestro Equipo',
    'aboutPage.ourTeamDesc': 'Conoce a los expertos apasionados que hacen de BTK Agency una agencia de primer nivel.',
    
    // About Page - Complete translations
    'aboutPage.founding.text': 'Fundada en 2020, hemos estado ayudando a empresas a crecer y prosperar en el mundo digital.',
    'aboutPage.ourStory.title': 'Nuestra Historia',
    'aboutPage.ourStory.paragraph1': 'BTK Agency fue fundada con una misión simple: ayudar a las empresas a prosperar en la era digital. Comenzamos como un pequeño equipo de profesionales de marketing y desarrollo que creían que cada empresa merece acceso a soluciones digitales de clase mundial.',
    'aboutPage.ourStory.paragraph2': 'Hoy, hemos crecido para convertirnos en una agencia de servicios digitales completa que ofrece sus servicios a clientes en múltiples industrias. Nuestro enfoque combina pensamiento estratégico, excelencia creativa y experiencia técnica para entregar resultados que superan las expectativas.',
    'aboutPage.ourStory.paragraph3': 'Estamos orgullosos de nuestro historial de éxito y las relaciones duraderas que hemos construido con nuestros clientes. Cada proyecto es una oportunidad para hacer una diferencia y estimular un crecimiento significativo.',
    'aboutPage.whyChoose.title': '¿Por qué Elegir BTK Agency?',
    'aboutPage.whyChoose.provenTrack': 'Registro de Éxito Proveniente',
    'aboutPage.whyChoose.provenTrackDesc': '150+ proyectos exitosos y creciendo',
    'aboutPage.whyChoose.expertTeam': 'Equipo de Expertos',
    'aboutPage.whyChoose.expertTeamDesc': 'Profesionales certificados con años de experiencia',
    'aboutPage.whyChoose.customSolutions': 'Soluciones Personalizadas',
    'aboutPage.whyChoose.customSolutionsDesc': 'Estrategias adaptadas a sus necesidades únicas',
    'aboutPage.whyChoose.ongoingSupport': 'Soporte Continuo',
    'aboutPage.whyChoose.ongoingSupportDesc': 'Soporte 24/7 y servicios de mantenimiento',
    'aboutPage.values.subtitle': 'Estos valores fundamentales guían todo lo que hacemos y forman la manera en que servimos a nuestros clientes.',
    'aboutPage.team.subtitle': 'Conoce a los expertos apasionados que hacen de BTK Agency una agencia de primer nivel.',
    'aboutPage.team.sarah.name': 'Sarah Johnson',
    'aboutPage.team.sarah.position': 'CEO & Fundadora',
    'aboutPage.team.sarah.bio': 'Visionaria digital con 10+ años de experiencia en transformación empresarial.',
    'aboutPage.team.sarah.expertise1': 'Estrategia Digital',
    'aboutPage.team.sarah.expertise2': 'Liderazgo',
    'aboutPage.team.sarah.expertise3': 'Innovación',
    'aboutPage.team.michael.name': 'Michael Chen',
    'aboutPage.team.michael.position': 'Director de Tecnología',
    'aboutPage.team.michael.bio': 'Experto en desarrollo web y arquitectura de sistemas escalables.',
    'aboutPage.team.michael.expertise1': 'Desarrollo Web',
    'aboutPage.team.michael.expertise2': 'Arquitectura',
    'aboutPage.team.michael.expertise3': 'DevOps',
    'aboutPage.team.david.name': 'David Rodriguez',
    'aboutPage.team.david.position': 'Director de Marketing',
    'aboutPage.team.david.bio': 'Estratega de marketing digital especializado en crecimiento de empresas.',
    'aboutPage.team.david.expertise1': 'Marketing Digital',
    'aboutPage.team.david.expertise2': 'SEO',
    'aboutPage.team.david.expertise3': 'Analytics',
    'aboutPage.team.emma.name': 'Emma Thompson',
    'aboutPage.team.emma.position': 'Diseñadora Senior',
    'aboutPage.team.emma.bio': 'Diseñadora creativa apasionada por crear experiencias visuales impactantes.',
    'aboutPage.team.emma.expertise1': 'Diseño UI/UX',
    'aboutPage.team.emma.expertise2': 'Branding',
    'aboutPage.team.emma.expertise3': 'Ilustración',
    'aboutPage.team.lisa.name': 'Lisa Wang',
    'aboutPage.team.lisa.position': 'Especialista en Contenido',
    'aboutPage.team.lisa.bio': 'Creadora de contenido estratégico que conecta marcas con audiencias.',
    'aboutPage.team.lisa.expertise1': 'Content Strategy',
    'aboutPage.team.lisa.expertise2': 'Copywriting',
    'aboutPage.team.lisa.expertise3': 'Social Media',
    'aboutPage.mission.title': 'Nuestra Misión',
    'aboutPage.mission.description1': 'Nuestra misión es empoderar a las empresas con soluciones digitales innovadoras que impulsen el crecimiento y la transformación. Creemos que cada empresa, sin importar su tamaño, merece acceso a tecnología de vanguardia y estrategias de marketing efectivas.',
    'aboutPage.mission.description2': 'Nos esforzamos por ser el socio digital de confianza que nuestros clientes necesitan para navegar el complejo panorama digital de hoy y construir un futuro próspero.',
    'aboutPage.vision.title': 'Nuestra Visión',
    'aboutPage.vision.description1': 'Visualizamos un futuro donde cada empresa tenga las herramientas y estrategias digitales necesarias para alcanzar su máximo potencial. Queremos ser reconocidos como la agencia que transforma no solo la presencia digital de nuestros clientes, sino también su impacto en el mundo.',
    'aboutPage.vision.description2': 'Nuestra visión es crear un ecosistema digital donde la innovación, la creatividad y los resultados se unen para crear un impacto duradero y significativo.',
    'aboutPage.cta.title': '¿Listo para Transformar tu Negocio?',
    'aboutPage.cta.subtitle': 'Únete a cientos de empresas que ya han experimentado el poder de nuestras soluciones digitales.',
    'aboutPage.cta.button': 'Obtener Cotización',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    
    // Footer
    'footer.quickLinks': 'Liens Rapides',
    'footer.services': 'Nos Services',
    'footer.contact': 'Contact',
    'footer.aboutUs': 'À propos de nous',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.privacy': 'Politique de confidentialité',
    'footer.copyright': '© 2025 BTK Agency. Tous droits réservés.',
    'footer.description': 'Votre partenaire digital pour transformer votre présence en ligne.',
    
    // Services
    'services.title': 'Nos Services',
    'services.subtitle': 'Des solutions digitales complètes pour transformer votre présence en ligne et atteindre vos objectifs business.',
    'services.seo.title': 'Optimisation SEO',
    'services.seo.description': 'Améliorez votre classement dans les moteurs de recherche et générez du trafic organique avec nos stratégies SEO éprouvées.',
    'services.advertising.title': 'Publicité Digitale',
    'services.advertising.description': 'Maximisez votre ROI avec des campagnes publicitaires ciblées sur toutes les plateformes majeures.',
    'services.design.title': 'Design de Marque',
    'services.design.description': 'Créez une identité de marque mémorable qui résonne avec votre audience cible.',
    'services.web.title': 'Développement Web',
    'services.web.description': 'Construisez des sites web rapides et responsifs qui convertissent les visiteurs en clients.',
    'services.analytics.title': 'Analyses et Insights',
    'services.analytics.description': 'Transformez les données en insights actionnables pour optimiser vos performances digitales.',
    'services.social.title': 'Marketing Réseaux Sociaux',
    'services.social.description': 'Engagez votre audience et construisez des connexions significatives sur les plateformes sociales.',
    
    // Hero
    'hero.title': 'Votre Croissance Digitale,Notre Expertise',
    'hero.subtitle': 'Transformez votre marque avec des stratégies de marketing digital de pointe. Nous créons des campagnes convaincantes qui génèrent des résultats et stimulent votre croissance business.',
    'hero.cta': 'Commencer aujourd\'hui',
    'hero.watchStory': 'Voir notre histoire',
    'hero.happyClients': 'Clients Satisfaits',
    'hero.projectsCompleted': 'Projets Réalisés',
    'hero.successRate': 'Taux de Réussite',
    'hero.support': 'Support',
    
    // About
    'about.title': 'À propos de BTK Agency',
    'about.subtitle': 'Nous sommes une agence de marketing digital visionnaire dédiée à transformer les entreprises grâce à des stratégies innovantes et une technologie de pointe.',
    'about.learnStory': 'Découvrir notre histoire',
    'about.happyClients': 'Clients Satisfaits',
    'about.projectsCompleted': 'Projets Réalisés',
    'about.successRate': 'Taux de Réussite',
    'about.yearsExperience': 'Années d\'Expérience',
    'about.innovationFirst': 'Innovation en Premier',
    'about.innovationFirstDesc': 'Nous restons en avance sur les tendances digitales pour livrer des solutions de pointe qui vous donnent un avantage concurrentiel.',
    'about.resultsDriven': 'Axé sur les Résultats',
    'about.resultsDrivenDesc': 'Chaque stratégie que nous implémentons est conçue pour livrer des résultats mesurables et maximiser votre retour sur investissement.',
    'about.clientPartnership': 'Partenariat Client',
    'about.clientPartnershipDesc': 'Nous croyons en la construction de partenariats à long terme, travaillant étroitement avec vous pour comprendre et atteindre vos objectifs.',
    'about.transparentProcess': 'Processus Transparent',
    'about.transparentProcessDesc': 'Transparence complète dans nos processus, tarifs et résultats. Vous saurez toujours exactement ce que nous faisons et pourquoi.',
    
    // Contact
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Prêt à transformer votre business ? Parlons-en !',
    'contact.email.title': 'Envoyez-nous un email',
    'contact.email.description': 'Envoyez-nous un email à tout moment',
    'contact.phone.title': 'Appelez-nous',
    'contact.phone.description': 'Lun-Ven de 8h à 18h',
    'contact.address.title': 'Visitez-nous',
    'contact.hours.title': 'Heures de travail',
    'contact.hours.days': 'Lundi - Vendredi',
    'contact.hours.time': '8:00 - 18:00 GMT+1',
    'contact.form.name': 'Nom',
    'contact.form.namePlaceholder': 'Votre nom',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'votre@email.com',
    'contact.form.subject': 'Sujet',
    'contact.form.subjectPlaceholder': 'Comment pouvons-nous vous aider ?',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Parlez-nous de votre projet...',
    'contact.form.send': 'Envoyer le message',
    
    // Common
    'learnMore': 'En savoir plus',
    'getStarted': 'Commencer',
    'contactUs': 'Nous contacter',
    'language': 'Langue',
    
    // Portfolio
    'portfolio.title': 'Notre Portfolio',
    'portfolio.subtitle': 'Découvrez nos projets les plus remarquables et l\'impact que nous avons créé pour nos clients.',
    'portfolio.filters.all': 'Tous les Projets',
    'portfolio.filters.web': 'Développement Web',
    'portfolio.filters.branding': 'Design de Marque',
    'portfolio.filters.marketing': 'Marketing Digital',
    'portfolio.filters.seo': 'SEO',
    'portfolio.viewProject': 'Voir le Projet',
    'portfolio.technologies': 'Technologies',
    'portfolio.results': 'Résultats',
    'portfolio.testimonial': 'Témoignage',
    'portfolio.loadMore': 'Charger Plus de Projets',
    
    // About Page
    'aboutPage.title': 'À propos de BTK Agency',
    'aboutPage.subtitle': 'Nous sommes une équipe passionnée d\'innovateurs digitaux dédiés à transformer les entreprises grâce à des stratégies innovantes et une technologie de pointe.',
    'aboutPage.values.title': 'Nos Valeurs',
    'aboutPage.team.title': 'Notre Équipe',
    'aboutPage.stats.title': 'Nos Statistiques',
    'aboutPage.innovation': 'Innovation',
    'aboutPage.innovationDesc': 'Nous restons en avance sur les tendances digitales pour livrer des solutions de pointe qui vous donnent un avantage concurrentiel.',
    'aboutPage.clientSuccess': 'Succès Client',
    'aboutPage.clientSuccessDesc': 'Votre succès est notre succès. Nous nous engageons à atteindre vos objectifs business.',
    'aboutPage.excellence': 'Excellence',
    'aboutPage.excellenceDesc': 'Nous maintenons les plus hauts standards dans chaque projet que nous entreprenons.',
    'aboutPage.collaboration': 'Collaboration',
    'aboutPage.collaborationDesc': 'Nous travaillons étroitement avec nos clients pour assurer un alignement et des résultats parfaits.',
    'aboutPage.happyClients': 'Clients Satisfaits',
    'aboutPage.projectsCompleted': 'Projets Réalisés',
    'aboutPage.clientSatisfaction': 'Satisfaction Client',
    'aboutPage.supportAvailable': 'Support Disponible',
    
    // About Page - Complete translations
    'aboutPage.founding.text': 'Fondée en 2020, nous aidons les entreprises à croître et prospérer dans le monde digital.',
    'aboutPage.ourStory.title': 'Notre Histoire',
    'aboutPage.ourStory.paragraph1': 'BTK Agency a été fondée avec une mission simple : aider les entreprises à prospérer à l\'ère digitale. Nous avons commencé comme une petite équipe de professionnels du marketing et du développement qui croyaient que chaque entreprise mérite d\'accéder à des solutions digitales de classe mondiale.',
    'aboutPage.ourStory.paragraph2': 'Aujourd\'hui, nous avons grandi pour devenir une agence de services digitaux complète qui sert des clients dans de multiples industries. Notre approche combine pensée stratégique, excellence créative et expertise technique pour livrer des résultats qui dépassent les attentes.',
    'aboutPage.ourStory.paragraph3': 'Nous sommes fiers de notre historique de succès et des relations durables que nous avons construites avec nos clients. Chaque projet est une opportunité de faire une différence et de stimuler une croissance significative.',
    'aboutPage.whyChoose.title': 'Pourquoi Choisir BTK Agency ?',
    'aboutPage.whyChoose.provenTrack': 'Historique de Succès Éprouvé',
    'aboutPage.whyChoose.provenTrackDesc': '150+ projets réussis et en croissance',
    'aboutPage.whyChoose.expertTeam': 'Équipe d\'Experts',
    'aboutPage.whyChoose.expertTeamDesc': 'Professionnels certifiés avec des années d\'expérience',
    'aboutPage.whyChoose.customSolutions': 'Solutions Personnalisées',
    'aboutPage.whyChoose.customSolutionsDesc': 'Stratégies adaptées à vos besoins uniques',
    'aboutPage.whyChoose.ongoingSupport': 'Support Continu',
    'aboutPage.whyChoose.ongoingSupportDesc': 'Support 24/7 et services de maintenance',
    'aboutPage.values.subtitle': 'Ces valeurs fondamentales guident tout ce que nous faisons et façonnent la façon dont nous servons nos clients.',
    'aboutPage.team.subtitle': 'Rencontrez les experts passionnés qui font de BTK Agency une agence de premier plan.',
    'aboutPage.team.sarah.name': 'Sarah Johnson',
    'aboutPage.team.sarah.position': 'CEO & Fondatrice',
    'aboutPage.team.sarah.bio': 'Visionnaire digitale avec 10+ ans d\'expérience en transformation d\'entreprise.',
    'aboutPage.team.sarah.expertise1': 'Stratégie Digitale',
    'aboutPage.team.sarah.expertise2': 'Leadership',
    'aboutPage.team.sarah.expertise3': 'Innovation',
    'aboutPage.team.michael.name': 'Michael Chen',
    'aboutPage.team.michael.position': 'Directeur Technique',
    'aboutPage.team.michael.bio': 'Expert en développement web et architecture de systèmes évolutifs.',
    'aboutPage.team.michael.expertise1': 'Développement Web',
    'aboutPage.team.michael.expertise2': 'Architecture',
    'aboutPage.team.michael.expertise3': 'DevOps',
    'aboutPage.team.david.name': 'David Rodriguez',
    'aboutPage.team.david.position': 'Directeur Marketing',
    'aboutPage.team.david.bio': 'Stratège en marketing digital spécialisé dans la croissance d\'entreprise.',
    'aboutPage.team.david.expertise1': 'Marketing Digital',
    'aboutPage.team.david.expertise2': 'SEO',
    'aboutPage.team.david.expertise3': 'Analytics',
    'aboutPage.team.emma.name': 'Emma Thompson',
    'aboutPage.team.emma.position': 'Designer Senior',
    'aboutPage.team.emma.bio': 'Designer créative passionnée par la création d\'expériences visuelles impactantes.',
    'aboutPage.team.emma.expertise1': 'Design UI/UX',
    'aboutPage.team.emma.expertise2': 'Branding',
    'aboutPage.team.emma.expertise3': 'Illustration',
    'aboutPage.team.lisa.name': 'Lisa Wang',
    'aboutPage.team.lisa.position': 'Spécialiste Contenu',
    'aboutPage.team.lisa.bio': 'Créatrice de contenu stratégique qui connecte les marques avec leurs audiences.',
    'aboutPage.team.lisa.expertise1': 'Stratégie de Contenu',
    'aboutPage.team.lisa.expertise2': 'Rédaction',
    'aboutPage.team.lisa.expertise3': 'Réseaux Sociaux',
    'aboutPage.mission.title': 'Notre Mission',
    'aboutPage.mission.description1': 'Notre mission est d\'autonomiser les entreprises avec des solutions digitales innovantes qui stimulent la croissance et la transformation. Nous croyons que chaque entreprise, quelle que soit sa taille, mérite d\'accéder à une technologie de pointe et des stratégies de marketing efficaces.',
    'aboutPage.mission.description2': 'Nous nous efforçons d\'être le partenaire digital de confiance dont nos clients ont besoin pour naviguer dans le paysage digital complexe d\'aujourd\'hui et construire un avenir prospère.',
    'aboutPage.vision.title': 'Notre Vision',
    'aboutPage.vision.description1': 'Nous visualisons un avenir où chaque entreprise a les outils et stratégies digitales nécessaires pour atteindre son plein potentiel. Nous voulons être reconnus comme l\'agence qui transforme non seulement la présence digitale de nos clients, mais aussi leur impact sur le monde.',
    'aboutPage.vision.description2': 'Notre vision est de créer un écosystème digital où l\'innovation, la créativité et les résultats se rejoignent pour créer un impact durable et significatif.',
    'aboutPage.cta.title': 'Prêt à Transformer votre Business ?',
    'aboutPage.cta.subtitle': 'Rejoignez des centaines d\'entreprises qui ont déjà expérimenté le pouvoir de nos solutions digitales.',
    'aboutPage.cta.button': 'Obtenir un Devis',
  }
};

function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export { LanguageProvider, useLanguage }; 